export const sliderDataApi = [
  {
    img: "./image/slider/slider01.png",
    title: "iPhone 14",
  },
  {
    img: "./image/slider/slider02.jpg",
    title: "iPad Mini",
  },
  {
    img: "./image/slider/slider03.jpg",
    title: "MacBook Pro",
  },
  {
    img: "./image/slider/slider04.png",
    title: "AirPods Pro",
  },
];

export const itemList = [
  {
    title: "iPhone",
    img: "./image/itemlist/item7.webp",
  },

  {
    title: "AirPods",
    img: "./image/itemlist/item5.jpg",
  },
  {
    title: "Mac mini",
    img: "./image/itemlist/item9.jpg",
  },
  {
    title: "Accessory",
    img: "./image/itemlist/item3.jpg",
  },
  {
    title: "iPad",
    img: "./image/itemlist/item4.jpg",
  },
  {
    title: "Mac",
    img: "./image/itemlist/item2.jpg",
  },
];

export const proApiSale = [
  {
    id: 1,
    title: "iPhone 11 64GB",
    img: "./image/pro/i1.webp",
    price: "800",
    imgSale: "./image/sale-icon.png",
    priceOld: "$ 1000",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
    category: "iphone11",
  },
  {
    id: 7,
    title: "iPhone 14 Pro Max 256GB",
    img: "./image/pro/i7.webp",
    price: "2080",
    priceOld: "$ 2600",
    imgSale: "./image/sale-icon.png",

    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
    category: "iphone14",
  },
  {
    id: 13,
    title: "MacBook Air M2 2022",
    img: "./image/pro/m2.webp",
    price: "2000",
    imgSale: "./image/sale-icon.png",

    priceOld: "$ 2600",
    category: "macair",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
  },
  {
    id: 15,
    title: "MacBook Pro 16 M1 Pro 2021",
    imgSale: "./image/sale-icon.png",

    img: "./image/pro/m4.webp",
    price: "2400",
    priceOld: "$ 3000",
    category: "macpro",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
  },
];

export const proApiHome = [
  {
    id: 4,
    title: "iPhone 13 Mini 128GB",
    img: "./image/pro/i4.webp",
    price: "1600",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
    category: "iphone13",
  },
  {
    id: 5,
    title: "iPhone 13 Pro Max 1TB",
    img: "./image/pro/i5.webp",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
    price: "2100",
    category: "iphone13",
  },
  {
    id: 9,
    title: "iPhone 14 Pro Max 1TB",
    img: "./image/pro/i9.webp",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
    price: "2900",
    category: "iphone14",
  },
  {
    id: 24,
    title: "iPad Pro M1 12.9 inch WiFi",
    img: "./image/pro/pd4.webp",
    price: "1500",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
    category: "ipadpro",
  },
];

export const proApi = [
  {
    id: 1,
    title: "iPhone 11 64GB",
    img: "./image/pro/i1.webp",
    price: "800",
    imgSale: "./image/sale-icon.png",
    priceOld: "$ 1000",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
    category: "iphone11",
  },
  {
    id: 4,
    title: "iPhone 13 Mini 128GB",
    img: "./image/pro/i4.webp",
    price: "1280",
    priceOld: "$ 1600",
    imgSale: "./image/sale-icon.png",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
    category: "iphone13",
  },
  {
    id: 5,
    title: "iPhone 13 Pro Max 1TB",
    img: "./image/pro/i5.webp",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
    price: "2100",
    category: "iphone13",
  },
  {
    id: 6,
    title: "iPhone 13 Pro Max 512GB",
    img: "./image/pro/i6.webp",
    price: "2000",
    category: "iphone13",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
  },
  {
    id: 7,
    title: "iPhone 14 Pro Max 256GB",
    img: "./image/pro/i7.webp",
    price: "2080",
    priceOld: "$ 2600",
    imgSale: "./image/sale-icon.png",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
    category: "iphone14",
  },
  {
    id: 8,
    title: "iPhone 14 Pro Max 512GB",
    img: "./image/pro/i8.webp",
    price: "2500",
    category: "iphone14",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
  },
  {
    id: 9,
    title: "iPhone 14 Pro Max 1TB",
    img: "./image/pro/i9.webp",
    imgSale: "./image/sale-icon.png",
    priceOld: "$ 2900",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
    price: "2320",
    category: "iphone14",
  },
  {
    id: 10,
    title: "iPhone 14 Pro 512GB",
    img: "./image/pro/i10.webp",
    price: "2300",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
    category: "iphone14",
  },
  {
    id: 11,
    title: "iPhone 12 128GB",
    img: "./image/pro/i11.webp",
    price: "1800",
    category: "iphone12",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
  },
  {
    id: 12,
    title: "Macbook Air 2020",
    img: "./image/pro/m1.webp",
    price: "1300",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
    category: "macair",
  },
  {
    id: 13,
    title: "MacBook Air M2 2022",
    img: "./image/pro/m2.webp",
    price: "2000",
    imgSale: "./image/sale-icon.png",
    priceOld: "$ 2600",
    category: "macair",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
  },
  {
    id: 14,
    title: "MacBook Pro 13 M1 2020",
    img: "./image/pro/m3.webp",
    price: "1800",
    category: "macpro",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
  },
  {
    id: 15,
    title: "MacBook Pro 16 M1 Pro 2021",
    imgSale: "./image/sale-icon.png",
    img: "./image/pro/m4.webp",
    price: "2400",
    priceOld: "$ 3000",
    category: "macpro",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
  },
  {
    id: 16,
    title: "Mac Mini M1 2020",
    img: "./image/pro/m5.webp",
    price: "900",
    category: "macmini",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
  },
  {
    id: 17,
    title: "MacBook Pro 13 inch M2 2022",
    img: "./image/pro/m6.webp",
    price: "2100",
    category: "macpro",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
  },
  {
    id: 18,
    title: "MacBook Pro 14  M1 Pro 2021",
    img: "./image/pro/m7.webp",
    price: "2000",
    category: "macpro",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
  },
  {
    id: 19,
    title: "iMac 24 inch M1 2021",
    img: "./image/pro/m8.webp",
    price: "2000",
    imgSale: "./image/sale-icon.png",
    priceOld: "$ 2500",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
    category: "imac",
  },
  {
    id: 20,
    title: "iMac 24 inch M1 2021",
    img: "./image/pro/m9.webp",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
    price: "2400",
    category: "imac",
  },

  {
    id: 22,
    title: 'iPad Pro M2 11" WiFi 128GB',
    img: "./image/pro/pd2.webp",
    price: "1600",
    priceOld: "$ 2000",
    imgSale: "./image/sale-icon.png",
    category: "ipadpro",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
  },
  {
    id: 23,
    title: "iPad Pro M1 11 inch WiFi",
    img: "./image/pro/pd3.webp",
    price: "920",
    category: "ipadpro",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
  },
  {
    id: 24,
    title: "iPad Pro M1 12.9 inch WiFi",
    img: "./image/pro/pd4.webp",
    priceOld: "$ 1500",
    price: "1300",
    imgSale: "./image/sale-icon.png",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
    category: "ipadpro",
  },
  {
    id: 25,
    title: "iPad Pro M1 11 inch WiFi",
    img: "./image/pro/pd5.webp",
    price: "1000",
    category: "ipadpro",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
  },
  {
    id: 26,
    title: "iPad Air 5 WiFi",
    img: "./image/pro/pd7.webp",
    price: "1400",
    category: "ipadair",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
  },
  {
    id: 27,
    title: "iPad Air 4 10.9 inch WiFi",
    img: "./image/pro/pd8.webp",
    price: "890",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
    category: "ipadair",
  },
  {
    id: 28,
    title: "AirPods 3",
    img: "./image/pro/air3.webp",
    priceOld: "$ 450",
    price: "360",
    imgSale: "./image/sale-icon.png",

    category: "airpods",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
  },
  {
    id: 29,
    title: "AirPods Pro Hộp sạc MagSafe",
    img: "./image/pro/air4.webp",
    price: "490",
    category: "airpods",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
  },
  {
    id: 30,
    title: "EarPods jack cắm Lightning",
    img: "./image/pro/air5.webp",
    priceOld: "$ 50",
    imgSale: "./image/sale-icon.png",
    price: "40",
    category: "earpods",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
  },
  {
    id: 31,
    title: "Power Core MagSafe",
    img: "./image/pro/a21.webp",
    price: "230",
    category: "powercore",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
  },
  {
    id: 32,
    title: "Power Core Polymer wireless",
    img: "./image/pro/a22.webp",
    priceOld: "$ 130",
    imgSale: "./image/sale-icon.png",
    price: "104",
    category: "powercore",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
  },
  {
    id: 33,
    title: "Power Core 20000mAh",
    img: "./image/pro/a23.webp",
    price: "160",
    category: "powercore",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
  },
  {
    id: 34,
    title: "Power Core 10000mAh 15W",
    img: "./image/pro/a24.webp",
    priceOld: "$ 100",
    imgSale: "./image/sale-icon.png",
    price: "80",
    category: "powercore",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
  },
  {
    id: 35,
    title: "Adapter Apple Type C 67W",
    img: "./image/pro/a12.webp",
    price: "130",
    category: "adapter",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
  },
  {
    id: 36,
    title: "Adapter Apple USB-C 20W",
    img: "./image/pro/a11.webp",
    priceOld: "$ 60",
    imgSale: "./image/sale-icon.png",
    price: "48",
    category: "adapter",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
  },
  {
    id: 37,
    title: "USB-C - Lightning 1m",
    img: "./image/pro/a13.webp",
    price: "80",
    category: "adapter",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
  },
  {
    id: 38,
    title: "Apple wireless MagSafe Charger ",
    img: "./image/pro/a14.webp",
    priceOld: "$ 190",
    imgSale: "./image/sale-icon.png",
    price: "152",
    category: "adapter",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
  },
  {
    id: 39,
    title: "Glass iPhone 14 Pro Max Belkin",
    img: "./image/pro/g11.webp",
    price: "290",
    category: "glass",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
  },
  {
    id: 40,
    title: "Glass iPhone 14 Plus UniQ",
    img: "./image/pro/g12.webp",
    price: "290",
    category: "glass",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
  },
  {
    id: 41,
    title: "Glass iPhone 14 Pro Max Jincase",
    img: "./image/pro/g12.webp",
    priceOld: "$ 130",
    imgSale: "./image/sale-icon.png",
    price: "104",
    category: "glass",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, perspiciatis neque molestiae minima hic eligendi. Voluptatibus architecto sed hic quisquam excepturi modi unde? Vel odio, illum facilis hic consectetur labore.",
  },
];
